# -*- coding: utf-8 -*-
"""gabung spk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gXw2OMbiBZM8Ooru0CT_YhRYIJte8Urx

menggabungkan sheet excel menjadi satu
"""

import numpy as np
import pandas as pd
import matplotlib as mt

df= pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 1 2021.xlsx",0)
#display(df)
df1 = pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 1 2021.xlsx",2)
#display(df)
df = df.append(df1)
#df

df= pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 2 2021.xlsx",0)
for i in range(2,26*2,2):
  df1 = pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 2 2021.xlsx",i)
  df = df.append(df1)
df

df= pd.read_excel("/content/drive/MyDrive/belajar/laporan.xlsx",0)
for i in range(1,12):
  df1 = pd.read_excel("/content/drive/MyDrive/belajar/laporan.xlsx",i)
  df = df.append(df1)
df

df.tail(40)

df= pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 1 2021.xlsx",0)
for i in range(2,49,2):
  df1 = pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 1 2021.xlsx",i)
  df = df.append(df1)

for i in range(0,49,2):
  df1 = pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 2 2021.xlsx",i)
  df = df.append(df1)

df

df= pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 1 2021.xlsx",0)
for i in range(2,49,2):
  df1 = pd.read_excel("/content/drive/MyDrive/belajar/DATA SPK SEMESTER 1 2021.xlsx",i)
  df = df.append(df1)
df.tail(20)

df.reset_index(drop=True,inplace=True)
df

a=df.columns
df1=df[a[0:6]]

df1

pd.isna(df1[a[3]][1])
for i in range(1,len(df1)):
  if pd.isna(df1[a[3]][i]) and not(pd.isna(df1[a[4]][i])) and not(pd.isna(df1[a[3]][i-1])):
    df1[a[3]][i] = df1[a[3]][i-1]
  if pd.isna(df1[a[2]][i]) and not(pd.isna(df1[a[4]][i])) and not(pd.isna(df1[a[2]][i-1])):
    df1[a[2]][i] = df1[a[2]][i-1]
  if pd.isna(df1[a[1]][i]) and not(pd.isna(df1[a[4]][i])) and not(pd.isna(df1[a[1]][i-1])):
    df1[a[1]][i] = df1[a[1]][i-1]
k=0
kk=0
kkk=0
for i in range(2,len(df1)):
  if not(df1.iloc[i].notnull()[3]) and sum(df1.iloc[i-2].notnull())==0 and sum(df1.iloc[i-1].notnull())==0:
    if k ==0 :
      k=1
      kk=i
  if i <len(df1)-2:
    if not(df1.iloc[i].notnull()[3]) and sum(df1.iloc[i+2].notnull())==0 and sum(df1.iloc[i+1].notnull())==0:
      if k == 1:
        k=2
        kkk=i+1
    #print("kkk =",str(kkk),"dan kk = " ,str(kk))
      if not(kk == 0) and not(kkk == 0):
        kkkk=""
        for j in range(kk,kkk):
          if "21" in str(df1[a[0]][j]):
            kkkk=df1[a[0]][j]
        #print(kkkk)
        for j in range(kk,kkk):
          df1[a[0]][j] = kkkk
        k=1
        kk=kkk
        kkk=0
df1

df1[a[0]][9]

kkkk="19 jan"
df1[a[0]][9] = kkkk

df["SEBAB KERUSAKAN"]=df["SEBAB KERUSAKAN"].str.lower()
#df["TANGGAL STOP"] = df["TANGGAL STOP"].dt.date
df["TANGGAL SIAP"] = df["TANGGAL SIAP"].dt.date

g= []
for i in range (len(df)):
  #print(i) 
  g.append(("extraction" in str(df["KERUSAKAN"][i])) | ("extraction" in str(df["SEBAB KERUSAKAN"][i])))
w = pd.Series(g)

g= []
for i in range (len(df)):
  #print(i) 
  g.append(("conveyor" in str(df["KERUSAKAN"][i])) | ("belt" in str(df["KERUSAKAN"][i])) | ("conveyor" in str(df["SEBAB KERUSAKAN"][i])) | ("belt" in str(df["SEBAB KERUSAKAN"][i])))
w = pd.Series(g)

df2=df[g]
df2.reset_index(drop=True,inplace=True)
df2

gg= []
a1,a2,a3,a4,a5,a6,a7 =0,0,0,0,0,0,0
for i in range (len(df2)):
  k= str(df2["SEBAB KERUSAKAN"][i])
  if ("anti slip" in k) | ("v-belt" in k) | ("nguras adonan" in k) | ("colator" in k) | ("mesh" in k) | ("metal" in k) | ("cooling conveyor trouble" in k) | ("timming belt" in k) | ("belt drive" in k) :
    gg.append(5)
    a5+=1
  elif ("motor" in k) | ("gearbox" in k) | ("gear box" in k) :
    gg.append(6)
    a6+=1
  elif ("jahitan" in k) | ("belt ngelipet" in k) | ("conveyor putus" in k) | ("sobek" in k) | ("finger" in k) | ("melar" in k) | ("imfonil" in k) | ("delaminasi" in k) | ("jahit belt" in k) | ("serabut" in k) | (("pin" in k) & ("belt" in k)) | (("belt" in k) & ("kendor" in k)) | (("belt" in k) & ("putus" in k)) :
    gg.append(3)
    a3+=1
  elif ("repair" in k) | ("patah" in k) | ("bubut" in k) | ("bearing" in k) | ("rantai" in k) |("selang" in k) |("roll tension" in k) |("rantai" in k) | ("pipa" in k) | ("spie" in k) :
    gg.append(1)
    a1+=1

  elif ("electrical" in k) | ("mcb" in k) | ("inverter" in k) | ("kabel" in k) | ("volt" in k) |("relay" in k) |("sensor" in k) | ("fuse" in k) | ("plc" in k)  | ("emergency" in k) | ("electrical" in k):
    gg.append(2)
    a2+=1
  elif ("setting" in k) | ("reposisi" in k) | ("kencangkan" in k) | ("pengecekan" in k) | ("tracking" in k):
    gg.append(4)
    a4+=1
  else :
    gg.append(7)
    a7+=1
  
print('kelas 1 =',a1,', kelas 2 =',a2,', kelas 3 =',a3,', kelas 4 =',a4,', kelas 5 =',a5,', kelas 6 =',a6,', kelas 7 =',a7) 
wg = pd.Series(gg)
wg

df2["kelas"]=wg

df2

p=[]
for i in range (len(df2)):
  k= str(df2["SEBAB KERUSAKAN"][i])
  kk = int(df2["kelas"][i])
  if (kk == 1) and (("motor" in k) | ("gearbox" in k) | ("gear box" in k)) :
    p.append(7)
  else:
    p.append(int(kk))
wg = pd.Series(p)
wg

df1.to_excel("output.xlsx")